# ============================================
# Stage 1: Build Flutter Web Application
# ============================================
FROM ghcr.io/cirruslabs/flutter:stable AS builder

USER root

WORKDIR /app

# Safe directory configuration for git
RUN git config --global --add safe.directory /app

# Optimize DART VM Memory for build to prevent OOM
ENV DART_VM_OPTIONS="--old_gen_heap_size=4096"

# Enable web support (idempotent)
RUN flutter config --enable-web

# Copy dependency files first for better caching
# Note: pubspec.lock will be generated by flutter pub get if missing
# Cache buster - INCREMENT THIS VALUE TO FORCE REBUILD ON DEPLOY
ARG CACHEBUST=2025-12-13-v7
COPY pubspec.yaml ./

# Get dependencies (generates pubspec.lock automatically)
RUN flutter pub get

# Copy source code
COPY . .

# Re-run pub get after copying source to ensure lockfile consistency
RUN flutter pub get

# Generate code (for Riverpod and Hive)
RUN dart run build_runner build --delete-conflicting-outputs

# Clean build environment to avoid conflicts
RUN flutter clean

# Build web application (CanvasKit renderer is now default)
# Added --no-tree-shake-icons to prevent potential font issues in some environments
RUN flutter build web --release --base-href="/" --no-wasm-dry-run --no-tree-shake-icons --verbose

# ============================================
# Stage 2: Serve with custom Dart server (with API proxy)
# ============================================
FROM dart:stable

WORKDIR /app

# Install SQLite3 library for FFI
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev wget xz-utils && rm -rf /var/lib/apt/lists/*

# Install FFmpeg with NVIDIA NVENC support from BtbN static builds
# This version includes hardware acceleration (NVENC/NVDEC/CUDA)
# Falls back gracefully to CPU if GPU not available
RUN wget -q https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz \
    && tar xf ffmpeg-master-latest-linux64-gpl.tar.xz \
    && mv ffmpeg-master-latest-linux64-gpl/bin/ffmpeg /usr/local/bin/ \
    && mv ffmpeg-master-latest-linux64-gpl/bin/ffprobe /usr/local/bin/ \
    && rm -rf ffmpeg-master-latest-linux64-gpl* \
    && chmod +x /usr/local/bin/ffmpeg /usr/local/bin/ffprobe

# Create directory for HLS stream output
RUN mkdir -p /tmp/streams && chmod 777 /tmp/streams

# Copy pubspec.yaml (required for dependencies)
COPY pubspec.yaml ./

# Copy lib directory (required for shared models)
COPY lib/ ./lib/

# Copy bin directory
COPY bin/ ./bin/

# Get dependencies
RUN dart pub get --directory=bin

# Copy built web application from builder stage
COPY --from=builder /app/build/web /app/web

# Expose port (internal only, not mapped to host)
EXPOSE 8089

# Serve web application with API proxy
WORKDIR /app
CMD ["dart", "run", "bin/server.dart", "--port", "8089", "--path", "/app/web"]
